### PR TITLE
Auto protobuf schema generation with Protobuf 2.0.2

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
Referring to #38, #39 and #40.

This is a merge between #38 and #40. A new change in this PR is bumping `protoc-rust` version to match the version of `protobuf` being used.

### CODE REVIEW

**Comment by psivesely** [comment]
When this is ready if you could clean up the git history (mostly the most recent commits) that would be :100: and I'll close #40.

**Comment by dingxiangfei2009** [comment]
I just remove the `wip` commits from this PR.

**Comment by psivesely** [comment]
You have `3.5.1` in 6 places in 2 files. It would be nice if we could set the protobuf version in a single place. E.g., create a top-level file called `protobuf-version.txt` that just reads `3.5.1` and then have `build.rs` and `install-protobuf.sh` both read that file. Or if you have another idea for how to simply maintain a single point of version declaration.

**Comment by dingxiangfei2009** [comment]
I have an idea to implement this. I will put `libprotoc 3.5.1` string into `PROTOC_VERSION` file at the project root. `build.rs` will confirm the version of `protoc` from the (compile time) `PROTOC_VERSION` *environment variable*. I will also set up the Travis CI to load the version file into the environment variable.

**Review by psivesely — APPROVED** [review]
LGTM!

**Comment by psivesely** [comment]
Why did you get rid of cargo cache? Could you have avoided whatever problem by adding a call to `cargo update` before building?

**Comment by dingxiangfei2009** [comment]
Oh yes, my bad. Making a new change now.

**Review by psivesely — APPROVED** [review]

**Pull request merged**
